In [1]:
import numpy as np
def convertfartocel(farenheit):
    celsius = (farenheit - 32)*5/9
    return celsius
return_vectorize=np.vectorize(convertfartocel)
temp=np.array([32, 68, 100, 212, 77])
print(return_vectorize(temp))

[  0.          20.          37.77777778 100.          25.        ]


In [2]:
def powerup(number,power):
    return number**power
powerup_vectorize=np.vectorize(powerup)
number=np.array([2, 3, 4, 5])
power=np.array([1, 2, 3, 4])
print(powerup_vectorize(number,power))

[  2   9  64 625]


In [7]:
matrix=np.array([[4,5,6],[3,-1,1],[2,1,-2]])
vector=np.array([7,4,5])
answer=np.linalg.solve(matrix,vector)
print(matrix)
print(answer)

[[ 4  5  6]
 [ 3 -1  1]
 [ 2  1 -2]]
[ 1.7027027   0.62162162 -0.48648649]


In [8]:
A=np.array([[10,-2,3],[-2,8,-1],[3,-1,6]])
B=np.array([12,-5,15])
answers=np.linalg.solve(A,B)
print(answers)

[ 0.48963731 -0.2253886   2.21761658]


In [23]:
from PIL import Image
with Image.open("birds.jpg") as Img:
    print(Img.mode)
    img_array=np.array(Img)
def save_img(arr,name,mode):
    img=Image.fromarray(arr,mode)
    img.save(name)
def flip_image(arr,name,mode):
    rotated_img=np.rot90(arr,2)
    save_img(rotated_img,name,mode)
def add_noise(arr):
    noise=np.random.normal(0,25,(100,100)).astype(np.int16)
    noise_image=arr.astype(np.int16)+noise
    noise_image=np.clip(noise_image,0,255)
    return noise_image.astype(np.uint8)
def brighten_image(arr,channel=0,amount=40):
    arr = arr.copy()
    arr[:, :, channel] = np.clip(arr[:, :, channel] + amount, 0, 255)
    return arr

def apply_mask(arr):
    arr = arr.copy()
    h, w = arr.shape[:2]
    start_x = w // 2 - 50
    start_y = h // 2 - 50
    arr[start_y:start_y + 100, start_x:start_x + 100] = [0, 0, 0]
    return arr



RGB
