In [17]:
import numpy as np

import random
a1 = np.array([1, 2, 3])
type(a1)

numpy.ndarray

In [6]:
array=np.arange(10,49)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [14]:
matrix=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
matrix_identity=np.identity(3)
print(matrix_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:

random_array=np.random.randint(1,10, size=(3,3,3))
print(random_array)

[[[4 6 2]
  [1 3 4]
  [9 5 6]]

 [[2 4 2]
  [3 8 9]
  [7 8 4]]

 [[2 4 4]
  [8 8 4]
  [4 9 3]]]


In [24]:
rand10x10=np.random.randint(1,50, size=(10,10))
maximum=np.max(rand10x10)
minimum=np.min(rand10x10)
print(f"{rand10x10}\n maximum: {maximum} minimum: {minimum}")

[[48 20 11  8 15 28 18 26 42 23]
 [37 32  6 38 44  5  1 23  6 42]
 [49 47 37 20 37 45 37 24 31 27]
 [ 1 24 10 36 22 23  7  7 45 40]
 [42 41 33 39 48  1  8 27 20 32]
 [24  3 49  2 23 14 22 32 23  1]
 [41 36 17 15 37 20 19 18  8 23]
 [ 9  6 28 21 17 48 14 40 35  9]
 [14 41 34 31 46  7 47 10 37 23]
 [23 23 15 26 41 27 33 12  3 17]]
 maximum: 49 minimum: 1


In [25]:
randvec=np.random.randint(1,10, size=(30))
mean=np.mean(randvec)
print(randvec, "mean: ", mean)

[3 8 9 9 5 9 6 1 7 9 8 6 7 8 9 2 4 8 1 6 3 8 3 8 4 2 1 1 1 3] mean:  5.3


In [39]:
matrix=np.random.randint(1,20 ,size=(5,5))
normat=(matrix-matrix.min())/(matrix.max()-matrix.min())

print(normat)



[[0.         0.47058824 0.35294118 0.70588235 0.05882353]
 [0.11764706 0.         0.58823529 0.23529412 0.88235294]
 [0.23529412 0.23529412 0.52941176 0.88235294 0.41176471]
 [0.88235294 0.88235294 0.70588235 0.70588235 0.11764706]
 [0.41176471 0.88235294 0.35294118 1.         0.52941176]]


In [42]:
matrix1=np.random.randint(1,10,size=(5,3))
matrix2=np.random.randint(1,10,size=(3,2))
product=np.dot(matrix1,matrix2)
print(product)


[[105 117]
 [ 51  51]
 [ 70  81]
 [ 61 114]
 [ 91 138]]


In [52]:
matrix1=np.random.randint(1,10,size=(3,3))
matrix2=np.random.randint(1,10,size=(3,3))
dotproduct=np.dot(matrix1,matrix2)
print(dotproduct)

[[ 66  38  87]
 [ 66  66  80]
 [ 89  87 115]]


In [44]:
matrix=np.random.randint(1,10,size=(4,4))
print(matrix)
print(matrix.T)

[[8 3 5 7]
 [4 9 6 1]
 [1 6 8 6]
 [1 7 1 7]]
[[8 4 1 1]
 [3 9 6 7]
 [5 6 8 1]
 [7 1 6 7]]


In [53]:
matrix=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
determinant=np.linalg.det(matrix)
print(f'{determinant}')

-9.51619735392994e-16


In [50]:
MatrixA=np.matrix([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
matrixB=np.matrix([[1,2,3,2],[4,5,6,4],[7,8,9,2]])
product=np.dot(MatrixA,matrixB)
print(product)

[[ 30  36  42  16]
 [ 66  81  96  40]
 [102 126 150  64]
 [138 171 204  88]]


In [51]:
matrix=np.random.randint(1,10,size=(3,3))
vector=np.random.randint(1,10,size=(3))
product=np.dot(matrix,vector)
print(product)

[ 50 110  48]


In [58]:
matrix=np.matrix([[1,2,3,4,5],[3,5,6,2,7],[4,2,6,2,7],[6,3,7,8,2],[5,8,2,9,6]])
row_wise=np.sum(matrix,axis=1)
column_wise=np.sum(matrix,axis=0)
print(row_wise, '\n', column_wise)

[[15]
 [23]
 [21]
 [26]
 [30]] 
 [[19 20 24 25 27]]


In [61]:
# Ax=b
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b=np.matrix([2,3,5])
x=b*np.invert(A)
print(x)

[[-59 -69 -79]]
